development: &development
  CLOUDAMQP_URL: demo
  DATABASE_URL: demo
  HEROKU_POSTGRESQL_JADE_URL: demo
  HEROKU_POSTGRESQL_ORANGE_URL: demo
  SCRAPE_COST_BASE: demo
  SCRAPE_COST_PER_PROFILE: demo
  SCRAPE_TIME_PER_PROFILE: demo
  SENDGRID_PASSWORD: demo
  SENDGRID_USERNAME: demo
  STRIPE_PUBLISHABLE_KEY: demo
  STRIPE_SECRET_KEY: demo
  HEROKU_OAUTH_TOKEN: demo
  HEROKU_OAUTH_KEY: demo

test:
  *development